setup: true
version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
workflows:
  setup:
    jobs:
      - continuation/setup:
          configuration_path: ".circleci/main.yml"
          parameters: /home/circleci/params.json
          pre-steps:
            - run:
                command: |
                  if [ -z "${CIRCLE_PULL_REQUEST##*/}" ]
                  then
                    IS_PR=false
                  else
                    IS_PR=true
                  fi
                  echo '$CIRCLE_PULL_REQUEST ' CIRCLE_PULL_REQUEST
                  echo '$IS_PR > ' $IS_PR
                  echo '{ "is_pr": '$IS_PR' }' >> /home/circleci/params.json