version: 2.1

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0

parameters:
 is_pr:
     description: Whether its a PR
     type: boolean
     default: "false"

jobs:
  validate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - run:
          name: Login to Org
          command: . build/auth.sh
      - run:
          name: Validate to Org
          no_output_timeout: 60m
          command: . build/validate.sh
  deploy:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - run:
          name: Login to Org
          command: . build/auth.sh
      - run:
          name: Deploy to Org
          no_output_timeout: 60m
          command: . build/deploy.sh

workflows:
  version: 2
  validate-dev-org:
    when: << pipeline.parameters.is_pr >>
    jobs:
      - validate
  deploy-dev-org:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - dev